<!DOCTYPE html>
<html lang="es">
	<head>
		<title></title>
	</head>
	<body>
		<?php
            $numfinal=0;
            $num=2;

			if($num<101) {
				echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                echo $num;
                echo "<br>";
                $numfinal=$num+$numfinal;
                $num=$num+2;
                
			}
            echo "La suma de todos los números es: ";
            echo $numfinal;
		?>
	</body>
</html>